version: '3'
services:
  app:
    container_name: happynewyear
    restart: always
    build: .
    command: npm run serve --host 0.0.0.0 --disable-host-check
    ports:
      - '80:8080'
      - '443:443'
    volumes:
      - ./:/app
       - /usr/src/app/my-app/node_modules
